Fix/defaultprops: DefaultProps에서 css 프로퍼티 제거
c-h-w-h/cds pull request #44
Opened 2023-03-03 12:05 UTC by prayinforrain

> 수정내역에 문제가 있어요! approve 하지 마세요.
자세한 내용은 내일(03/06) 회의 때 공유할게요

## 🤠 개요

- emotion.jsx에서 정의된 기본 `css` 프로퍼티와 `DefaultProps`의 `css` 프로퍼티 네이밍이 중복되는 문제가 있었어요.
- 아래 이슈에서 이야기한 결론에 따라 `DefaultProps` 인터페이스에서 `css`를 삭제했어요.
- #43
- 지금 각자 브랜치에서 작업중인 내용이 있다면 이 PR에 맞추어 수정해주세요!

## 💫 설명

스토리북에서 예제를 좀 더 가시적으로 보여주기 위해 컴포넌트에 css를 삽입한 경우가 있는데, 이제 이를 위해서는 css를 `Template.bind` 함수의 인자로 넣어주어야 해요. 커밋에 함께 변경된 스토리 파일들을 보면 다들 금방 이해하실거에요.  
참고로 `bind` 함수는 함수에 인자를 넣어서 다시 생성하는 `Function`의 메소드에요. 저만 몰랐을 수도 있는데 처음 알았어요.  
https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Function/bind  
  
그런데 그럼 이게 더 좋은 모양새냐? 하면 잘 모르겠어요. 근데 엄청 직관성 떨어지거나 안 좋은 코드는 아닌 듯 해서 이대로 가면 될 것 같아요. 익숙하지 않아서 이상하게 느껴지는걸수도
  
선민님이 물어보셔서 설명하려고 생각해보니 막상 emotion이 어떤 식으로 작동하는지 딱 명료하게 정리는 안되네요. 결국 언젠가는 제대로 공부해야 할 것 같아요...

## 📷 스크린샷 (Optional)

2023-03-05 06:11 UTC, leesunmin1231 commented
옹 고생하셨어요!!
궁금한게 있는데, 원래 기존에 css: css`어쩌구` 를 args로 넣어주던 거랑 Template에 바인딩으로 넣어주는 거랑 적용되는 방식이 어떻게 다른건가요??
Template bind로 props 넣어주는 거랑 args에 props 넣어주는 거랑 똑같이 작동해야하는거 아닌가요...?

2023-03-05 06:25 UTC, prayinforrain commented
> 옹 고생하셨어요!! 궁금한게 있는데, 원래 기존에 css: css`어쩌구` 를 args로 넣어주던 거랑 Template에 바인딩으로 넣어주는 거랑 적용되는 방식이 어떻게 다른건가요?? Template bind로 props 넣어주는 거랑 args에 props 넣어주는 거랑 똑같이 작동해야하는거 아닌가요...?

작동방식은 같은 걸로 보이는데 제생각에는 해당 컴포넌트가 명시적으로 받는 인자만 args에 들어가는 것 같아요.  
args에 css를 그대로 두니까 타입 에러가 나더라구요

2023-03-05 07:29 UTC, leesunmin1231 requested changes

2023-03-05 07:29 UTC, leesunmin1231 commented on src/components/@layout/Flexbox/Flexbox.stories.tsx
>    `,
헐 우재님 오류 발견!!!!!!!! 이거 스타일 적용 안되고 있어요!!!!
Container는 이렇게 넣어준거 스타일 적용 잘 되는데, 그 Template 함수에서 컴포넌트 리턴하는 경우는 이렇게 스타일 적용이 안돼요!

2023-03-05 07:44 UTC, prayinforrain commented on src/components/@layout/Flexbox/Flexbox.stories.tsx
>    `,
아.. 색상만 확인하고 되는구나 넘겼는데 기본 템플릿에서 배경색을 이중으로 지정하고 있었네요  
어떻게 해야 납득 가능한 형태가 될지 잘 모르겠어요. 일단 보류할게요 다들 approve하지 마세요

2023-03-05 08:16 UTC, prayinforrain commented on src/components/@layout/Flexbox/Flexbox.stories.tsx
>    `,
때마침 내일 회의니까.. 내일 이야기해봐요  
답을 못찾겠어요 😭

2023-03-05 08:17 UTC, leesunmin1231 commented on src/components/@layout/Flexbox/Flexbox.stories.tsx
>    `,
음 저도 좀 뒤져볼게요. 저도 이거 쓰던 참이라.. 해결책 찾으면 내일 들고갈게요

2023-03-05 08:19 UTC, prayinforrain commented on src/components/@layout/Flexbox/Flexbox.stories.tsx
>    `,
복잡한 문제가 될 것 같으니 우선은 기존 방식대로 구현해주세요~

2023-03-05 09:16 UTC, leesunmin1231 commented on src/components/@layout/Flexbox/Flexbox.stories.tsx
>    `,
👍

2023-03-06 04:44 UTC, dohun31 approved these changes

2023-03-06 04:53 UTC, leesunmin1231 approved these changes

2023-03-06 04:53 UTC, iyu88 approved these changes
수고하셨어요~

2023-03-06 04:57 UTC, merged