Feat/input: Input 컴포넌트 구현
c-h-w-h/cds pull request #48
Opened 2023-03-05 14:21 UTC by leesunmin1231

## 🤠 개요

이슈번호: #46 
Input 컴포넌트 구현.

## 💫 설명

https://m2.material.io/components/text-fields

위 링크를 참고하기는 했는데 많은 기능을 덜어냈어요(?)
디자인 잡는게 세상 제일 어려워요.. 
추가해주면 좋을 거 같다 하는 기능이나 UI는 피드백으로 달아주시면 추가해볼게요!

비제어, 제어 모두 사용할 수 있어요.

### 비제어로 사용할 때
- props: inputRef ([RefObject<T> 타입](https://driip.me/7126d5d5-1937-44a8-98ed-f9065a7c35b5)이라 초기값은 null로 설정해주세요)

### 제어로 사용할 때
- props: onChange (change 이벤트 발생했을 때, 이벤트 핸들러), isValid (유효성 검사 통과 유무 boolean)
- isValid는 default 값을 true로 설정해둬서 props를 넘겨주지 않으면 스타일이 변하지 않아요. 

## 📷 스크린샷 (Optional)
### 비제어 컴포넌트 기본 스타일
![uncontrolledDefault](https://user-images.githubusercontent.com/81913106/222966167-2a7805dd-2660-4c71-a239-5340a9b76578.gif)

### 비제어 컴포넌트 커스텀 스타일
![uncontrolledCustom](https://user-images.githubusercontent.com/81913106/222966174-7a8fcbaa-1271-4f0e-91e0-d28c4b622d05.gif)

### 제어 컴포넌트
![controlled](https://user-images.githubusercontent.com/81913106/222966176-18e7a6bc-1188-4087-bf46-cbd252de7c03.gif)

2023-03-06 04:01 UTC, se030 requested changes

2023-03-06 04:01 UTC, se030 commented on src/components/Input/index.tsx
> +interface InputProps extends DefaultProps<HTMLInputElement> {
- isValid는 이런값 말고 https://developer.mozilla.org/en-US/docs/Web/CSS/:valid 사용하는게 좋지 않을까요? 스타일링도 psuedo class로 할 수 있어요.
- inputRef도 어차피 Input 컴포넌트에 붙이는 ref니까 props 정의보다는 forwardRef로 내려주는게 더 좋은 것 같아요.
- 또 이거 두가지 반영하면 InputProps는 이미 DefaultProps<InputElement>에 전부 포함되어 있어서 따로 정의할 필요 없어보여요!

2023-03-06 04:05 UTC, leesunmin1231 commented on src/components/Input/index.tsx
> +interface InputProps extends DefaultProps<HTMLInputElement> {
오호 넹! 반영할게여!!

2023-03-06 04:20 UTC, se030 commented on src/components/Input/index.tsx
> +  onChange?: ChangeEventHandler<HTMLInputElement>;
```suggestion
  id: string;
  name?: string;
```

해서 name 없는 경우에는 id 값으로 넣어주게요!

2023-03-06 05:22 UTC, dohun31 commented on src/components/Input/index.tsx
> +      id={id}
placeholder말곤 받은거 바로 넣어주는것 같은데 얘네도 `...props`에 같이 넣어주면 안되나요??

2023-03-06 05:22 UTC, dohun31 commented on src/components/Input/index.tsx
> +          : `0.1rem solid ${error}`,
```suggestion
        border: `0.1rem solid ${isValid ? primary100 : error}`
```
앞에 rem solid는 중복되는데 삼항연산자를 여기에 사용하는건 가독성이 별로인가요?

2023-03-06 05:24 UTC, se030 commented on src/components/Input/index.tsx
> +          : `0.1rem solid ${error}`,
저두 이거 추천 !!!!

2023-03-06 05:26 UTC, leesunmin1231 commented on src/components/Input/index.tsx
> +          : `0.1rem solid ${error}`,
아항 바꿀게여!

2023-03-06 05:30 UTC, iyu88 commented on src/components/Input/index.tsx
> +  ...props
font-size 나 line-height 스타일 값을 명시적으로 받아서 내려줘도 괜찮을 것 같아요~

2023-03-06 07:04 UTC, leesunmin1231 commented on src/components/Input/index.tsx
> +  ...props
추후에 컴포넌트 디자인 방향이 결정 되면 반영해볼게요~!!

2023-03-20 02:31 UTC, se030 approved these changes

2023-03-20 02:58 UTC, merged