Feat/carousel: Carousel 컴포넌트 구현
c-h-w-h/cds pull request #64
Opened 2023-03-20 13:42 UTC by leesunmin1231

## 🤠 개요

- #60 
- 이슈에 첨부한 링크 참고하여 구현하였습니다. 
- 전체적인 UI는 애플 공식 홈페이지, idus 어플 참고하였습니당
[애플 홈페이지](https://www.apple.com/kr/store?afid=p238%7CsiADh6hbK-dc_mtid_18707vxu38484_pcrid_650480254001_pgrid_16348496961_pntwk_g_pchan__pexid__&cid=aos-kr-kwgo-Brand--slid---product-)

## 💫 설명

- 디자인을 어떻게 해야할까 고민을 많이 했는데 모바일 퍼스트라는 점을 가장 크게 고려했어요.
- 처음에 넣어줄 내용들을 배열 타입 props로 받았다가, 너무 유연함이 없는 컴포넌트인 거 같아서 Compound component 패턴으로 리팩토링했습니다.
- Carousel 컴포넌트 안에 자식 컴포넌트로 여러개의 Card 컴포넌트가 있는 형태이며, Card 컴포넌트 내에 있는 자식 요소들은 하나의 카드 안에 들어가게 됩니다.
- 가로 스크롤과 버튼으로 slide를 이동할 수 있습니다.
- grid layout의 경우 일부로 하단에 진행률을 표시해주지 않았는데, 넣는게 좋을지 아직 고민중입니다.
- 오류가 있을 수 있어요... 다들 꼭 스토리북 확인해주시면 감사하겠습니당

### props
cardLayout: 'inline' | 'grid' => 캐러셀 layout
cardWidth: number => 캐러셀에 들어갈 카드 하나의 너비
cardHeight: number => 캐러셀에 들어갈 카드 하나의 높이

cardLayout 제외하고 optional 이고, cardLayout의 경우 default를 inline으로 설정해두었습니다.
cardWidth, cardHeight는 카드 하나의 규격을 커스텀 할 수 있도록 넣어주었습니다.

## 📷 스크린샷 (Optional)
### Default inline layout
<img width="756" alt="image" src="https://user-images.githubusercontent.com/81913106/226356054-db3d3807-a086-4612-9632-555bdbd58138.png">

### Custom inline layout
<img width="906" alt="image" src="https://user-images.githubusercontent.com/81913106/226357014-9bf7826e-28e7-4e2b-802c-e2d0c6bdcbe2.png">

### Default grid layout
<img width="911" alt="image" src="https://user-images.githubusercontent.com/81913106/226357073-bb338a6e-8932-4b26-8a0b-1e23479404b0.png">

### Custom grid layout
<img width="901" alt="image" src="https://user-images.githubusercontent.com/81913106/226357140-474130bc-2297-4446-85d3-c47b4026e1fa.png">

2023-03-20 16:55 UTC, prayinforrain commented on src/components/Carousel/NavigationButton.tsx
> +    </Center>
개인적인 생각인데.. 이 버튼을 표시하기 위해서 캐러셀 표시 범위가 제한되는 게 별로 보기 좋은 레이아웃이 아닐 것 같아요. 이유는 레퍼런스로 참고하신 애플의 캐러셀이 양옆이 컨트롤러 버튼에 의해 잘린다고 생각하면.. 글로 설명이 안되는데 더 필요하시면 내일 설명할게요 ㅋㅋ...
캐러셀 카드들 위로 버튼이 놓이도록 수정하는게 좋을 것 같아요.

2023-03-20 16:55 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +    cardLayout === 'grid' ? Math.ceil(totalChildren / 2) : totalChildren;
제가 이해한게 맞다면 grid인 경우 두 줄로 표시되니 2로 나누어 개수를 세는 걸로 보이는데요,  
2행으로 나누어 표시하는 것 === grid이라고 생각하지는 않아요. 아예 line 수를 props로 받거나.. 다른 이름을 사용하는게 좋을 것 같아요.

2023-03-20 16:55 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +  }, 200);
우리 loadsh 깔려있는거 이거 보고 알았어요 ㅋㅋ... debounce로 브라우저 크기 변경 처리하신거 꼼꼼해요 😆

2023-03-20 16:55 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +            {'〈'}
텍스트보단 아이콘을 찾아보면 좋을 것 같아요~! 폰트에 이런 부분을 맡기고 싶지 않아요

2023-03-20 16:55 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
저한테 보여주셨을 때랑은 다른 부분에서 고민이 보이네요. 좀 더 좋은 방법을 생각해봐요 우리 ㅋㅋㅋ

그거랑 별개로 Dot의 개수가 직관적이지 못한 느낌을 받았어요. 제 개인적인 생각은 카드의 개수만큼 Dot가 존재해야 한다고 생각하거든요. 캐러셀 width가 카드 하나의 width의 두 배 이상이면 이게 일치하지 않는 것 같아요.

장기적으로는 Dot을 클릭했을 때 해당 페이지로 이동이 가능하도록 구현하면 더 좋겠어요. 지금은 사실 클릭 영역이 좁아서 이 상태에서 구현하면 의미가 없을 것 같고..

2023-03-20 16:58 UTC, prayinforrain commented
멋있어요~! 너무 이뻐요  
리뷰에 자잘한 생각을 적어뒀고 하나만 더 추가할게요. 지금 구현된 캐러셀에서 선택된 페이지가 오는 위치를 지정할 수 있을까요?  
그러니까 음.. 애플의 캐러셀을 예로 들면
![image](https://user-images.githubusercontent.com/46566891/226412860-b5335580-8b00-42ce-a3af-dc2f240bb0cf.png)  
선택된 카드가 이 체크한 위치에 오도록 되어 있고, usecase에 따라 선택된 카드가 캐러셀의 중앙에 오도록 하고싶을 수도 있을 것 같아요. 이 부분을 어떻게 제어할 수 있는지 궁금해요.

2023-03-21 02:08 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
어제 자면서 생각해봤는데, 어차피 각각의 dot가 page들과 순서대로 매칭되는데 정말 index를 사용하면 안될까? 하는 생각이 들었어요. 그래서 방금 [이 글](https://robinpokorny.medium.com/index-as-a-key-is-an-anti-pattern-e0349aece318)을 찾았는데,

>1. the list and items are static–they are not computed and do not change;
>2. the items in the list have no ids;
>3. the list is never reordered or filtered.
>
>When all of them are met, you may safely use the index as a key.

라고 하네요. 좀 찝찝하지만 지금같은 경우 dot가 재정렬되거나 필터링되지 않고, dot 자체가 index에만 영향을 받는 컴포넌트여서 일반적으로 이야기하는 부작용이 없으니 사용해도 괜찮아 보여요. 음.. 다른 분들 의견을 기다릴게요 모르겠어요 ㅠㅠ

2023-03-21 05:13 UTC, se030 commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
> 제 개인적인 생각은 카드의 개수만큼 Dot가 존재해야 한다고 생각하거든요.

저도 동의해요. 이미 만들어져서 수정하기 까다롭겠지만 ㅠㅠ 페이지보다는 아래처럼 카드 개수를 나타내는게 직관적이고 익숙한 인터페이스라고 생각해요!

<img width="705" alt="image" src="https://user-images.githubusercontent.com/63814960/226522202-149c465b-98dd-4de0-8dcb-119b8043029e.png">

2023-03-21 05:13 UTC, se030 commented on src/components/Carousel/index.tsx
> +  }, 200);
음 package.json에 없는거보면 저희가 설치한건 아니고 다른 라이브러리 의존성으로 설치된 것 같은데 명시적으로 인스톨 해주시면 좋을 것 같아요!

2023-03-21 05:13 UTC, se030 commented on src/components/Carousel/index.tsx
> +  itemList: { img?: string; content?: string }[];
안쓰이는 프로퍼티 제거해주세요 ㅎㅎ

2023-03-21 05:13 UTC, se030 commented on src/components/Carousel/index.tsx
> +  const getCardSize = () => {
이런 유틸 함수는 필요한 것들을 인자로 받고 컴포넌트 외부로 빼는게 더 좋을 것 같아요. (근데 인자가 생각보다 여러개라서 여기에서 정의하는게 깔끔하긴 하네요)

그리고 CAROUSEL_SLIDE 라는 네이밍은 저 상수의 역할을 제대로 나타내지 못하는 것 같아요. CAROUSEL_SLIDE_STYLE은 어때요?

```ts
const defaultSize = cardLayout === 'grid' ? CAROUSEL_SLIDE.grid : CAROUSEL_SLIDE.inline;

const defaultSize = CAROUSEL_SLIDE_STYLE[cardLayout]; // 이렇게 쓰는게 좋을 것 같고

cardWidth && Object.assign(defaultSize, { WIDTH: cardWidth });
cardHeight && Object.assign(defaultSize, { HEIGHT: cardHeight}); // 조건문이 많아서 이런식으로 작성할 수도 있을 것 같아요

return defaultSize;
```

그리고 cardLayout으로 grid를 넣으신 이유가 있나요?? 여러줄짜리 캐러셀이라면 각각의 행이 별개의 컨트롤을 가지는게 좋다는 생각이 드는데 그리드 레이아웃을 고려하신 이유가 궁금해요!

2023-03-21 06:16 UTC, iyu88 approved these changes
수고 많으셨어요! 👍👍👍
변경 사항이 많을 것 같은데 천천히 해주세요~ 😊

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  const totalChildren = Children.count(children);
와 이거 처음 봐요..👍 Children도 공부해봐야겠네요!!

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  GAP: number;
이렇게 interface 에서 케이스로 알려주는거 좋은 것 같아요 👍👍👍
제가 만든 컴포넌트에도 적용해봐야겠네요~

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +`;
혹시 이 친구는 Layout 컴포넌트 중에서 Flexbox로 대체 가능할까요?

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +`;
혹시 Slider를 새로운 스타일 컴포넌트로 선언한 이유가 있을까요?
개인적으로는 Flexbox로 대체하고 css로 필요한 속성들을 넘겨주면 좋을 것 같아요!
왜냐하면 Slider가 외부로 노출되는게 아니여서 별도의 식별자를 부여하지 않아도 될 것 같기 때문이에요!

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  }
`-ms-overflow-style: none;` 속성도 같이 넣어주면 좋을 것 같아요.
IE (🪦🙏) 와 엣지 브라우저를 위해서요~
https://reference.codeproject.com/css/-ms-overflow-style

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +`;
> 장기적으로는 Dot을 클릭했을 때 해당 페이지로 이동이 가능하도록 구현하면 더 좋겠어요. 지금은 사실 클릭 영역이 좁아서 이 상태에서 구현하면 의미가 없을 것 같고..

우재님이 말씀하신 것처럼 구현하기 위해 스타일 컴포넌트 말고 리액트 컴포넌트로 분리하면 좋을 것 같아요~

그리고 8px 로 되어 있는 부분을 보니까 최소 클릭 크기가 있었던 것 같아서 아래 내용을 찾아봤어요.

<img width="1293" alt="스크린샷 2023-03-21 15 10 00" src="https://user-images.githubusercontent.com/31645195/226530442-cb4286cf-256b-48b8-a6b5-b55ebf00757c.png">

클릭 가능한 부분은 최소 48px이 되어야 하고 내용이 그것보다 작을 경우 패딩을 주면 좋다고 하니 나중에 혹시 클릭 이벤트가 생긴다면! 패딩도 추가해주면 좋을 것 같아요
아래 전문 링크입니다.

https://web.dev/accessible-tap-targets/

2023-03-21 06:16 UTC, iyu88 commented on src/components/Carousel/Carousel.stories.tsx
> +          src="https://user-images.githubusercontent.com/81913106/226325428-7909f3c2-4790-4c8b-ba2c-6ada349cb33d.png"
`DUMMY_IMG` 혹은 `DUMMY_SRC` 라는 변수에 할당하면 코드를 조금 더 정리할 수 있을 것 같아요~

2023-03-21 07:17 UTC, se030 commented on src/components/Carousel/index.tsx
> +  const totalChildren = Children.count(children);
https://react.dev/reference/react/Children

2023-03-22 04:23 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +`;
ㅜㅜ Flexbox 내부에 default로 설정된 css들이 많아서 제대로 동작을 안해요... css props를 이것 저것 많이 내려줘야할 거 같아 그냥 이렇게 했습니당..

2023-03-22 04:32 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +`;
Container로 바꿔줬습니당!

2023-03-22 04:38 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +`;
이것도 Container로 대체했습니당!

2023-03-22 04:48 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
음 고민을 해봤는데 하단에 진행률을 표시해줬던 이유는 캐러셀은 명확한 맥락이 있어야 한다는 부분을 고려해서 였어요. 현재 몇번째 슬라이드를 보고 있고 총 몇개의 슬라이드가 있는지 표시해주는 부분이에요.
밑에 Dot은 사실상 진행률만 표시해주는 역할이지 페이지네이션의 기능이 아니라서 클릭하는게 어울리지 않아보여요.. 우재님이랑 현빈님이 말씀하신것처럼 클릭이 되는 영역이라면 최소한의 클릭 크기가 있어야 하는데, 클릭이 가능한 기능이라면 차라리 페이지네이션 처럼 페이지 번호를 붙여서 사용하는 방향이 맞지 않나 싶네요.
지금은 페이지네이션이 아니라 캐러셀이라서 클릭으로 페이지 이동이 조금 어색한거 같아요.
다른 분들 의견은 어떠세요??

2023-03-22 06:20 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
> 현재 몇번째 슬라이드를 보고 있고 총 몇개의 슬라이드가 있는지 표시해주는 부분이에요.

저는 이 표현과 pagination의 의미가 통한다고 생각해요. 예시로 스팀의 메인페이지 캐러셀을 가져왔어요.  

![image](https://user-images.githubusercontent.com/46566891/226815754-311391bf-b6b2-4de9-829d-41d09df6956d.png)
저 캐러셀은 현재 할인중인 게임 타이틀들을 모아놓은 캐러셀이고, 하단에 Dot 컴포넌트의 역할을 하는 부분이 있는데, 총 7페이지가 있다는 것을 알 수 있어요. 어떤 사용자는 이 페이지를 7페이지까지 쭉 훑어보면서 어떤 게임이 있나 살펴 볼거에요.   

만약 7페이지까지 살펴본 후, 3페이지에 있던 게임을 더 자세히 보고 싶다면 어떻게 해야할까요? 왼쪽이든 오른쪽이든 3~4번 버튼을 누른 후에야 그 페이지에 도달할 수 있어요. 저는 **여기서 이미 현재 진행률을 표시해 주는 의미를 잃었다고 생각해요.** 결국 표시되는 진행률과 상관 없이 내가 원하는 정보가 나올 때까지 무한히 화살표를 눌러야 할테니까요. 이 문제는 캐러셀의 카드 수가 많아질수록 심화될거에요. 참고로 저 UI에서도 Dot를 눌러 해당 페이지로 즉시 이동할 수 있어요.  

페이지네이션에 숫자가 포함되어 있다면 더 직관적이겠지만, 숫자가 없더라도 페이지네이션인 건 아니에요. 페이지네이션의 핵심 아이디어는 한 번에 표시하기 너무 많은 데이터를 분할해서 표시한다는 점이라고 생각해요. 만약 구글의 페이지네이션에서 숫자가 빠진다 하더라도, 사용자는 '이 만큼의 정보가 있겠구나.' 하고 예측할 수 있을거에요.  
![image](https://user-images.githubusercontent.com/46566891/226817401-8d295a7d-b5b2-48b1-ab9c-8a18277d7e77.png)  

제 생각은 `지금 Dot의 역할과 페이지네이션이 일치한다`에요. 자꾸 게임을 예시로 들게 되는데.. Dot에 페이지 넘버가 포함된 캐러셀도 있어요 ㅎㅎ.. 
![image](https://user-images.githubusercontent.com/46566891/226817617-4c0b637b-41f8-4818-bc65-7219ed8ce6f6.png)

물론 제가 _클릭하면 해당 페이지로 이동하도록 구현하면 좋을 것 같다_ 고 한 부분은 모바일에서는 거의 사용하지 않는 것으로 알고 있어요. 하지만 우리 최종 목표가 모바일에 국한되어 있지 않아서 장기 목표를 제안해봤습니다~

2023-03-22 06:44 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
음 제가 처음 생각했던건 모바일 퍼스트이구 후에 웹으로 확장가능성을 고려한다. 정도여서 웹과 모바일의 ui는 동일하게 할 생각이었어요.
그래서 모바일에서 클릭시 이동이 부자연스럽다고 생각했습니당
아래 idus도 진행률은 숫자로만 표현하는 형태로 모바일, 웹 ui가 거의 비슷하더라구요.
![image](https://user-images.githubusercontent.com/81913106/226822130-037a7422-8020-4a0a-9c96-d667cce81d4d.png)
![image](https://user-images.githubusercontent.com/81913106/226822405-51e78930-36d2-4de5-bc9b-ff0b661d5dcd.png)
원하는 정보가 나올 때까지 무한히 화살표를 누르는 건 가로스크롤이 가능하도록 했으니까 어느정도 해결이 되었다고 생각했는데, 확실히 웹을 생각하면 페이지네이션 처럼 클릭이 가능한게 좋겠네요

흠 그럼 웹이랑 모바일 ui를 좀 다르게 해야할까요? 고민이 되네여..

2023-03-22 07:35 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
음 그럼 방향이 숫자와 Dot 여부를 각각 옵셔널하게 받을 수 있게 한 다음에 

기기에 따라 옵션(props)가 달라지게 되는 것일까요?

2023-03-22 07:35 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  const totalChildren = Children.count(children);
그냥 이런게 있구나~ 하고 넘어가겠습니다 ㅎㅎ

2023-03-22 07:46 UTC, se030 commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
저도 dot 클릭했을 떄 이동하는건 사용자 경험에 플러스 요소라는 의견에는 동의해요! + 이걸 굳이 숫자로 표시할 필요는 없는 것 같아요. 피그마 디자인도 dot로 되어있구요.
근데 모바일 UI부터 만들고있는 만큼 이 기능 추가없이 지금대로 진행해도 충분할 것 같아요 ~ 저는 진행률 정보를 남은 컨텐츠가 얼마나 있는지 확인하려고 쓰기도 하거든요.
사실 모바일은 화면이 작다보니 진행률을 표시해주고 이동 기능은 없는게 더 흔한 것 같아요 ..ㅎㅎ 대신 원형큐..로 되어있는 경우가 많고(마지막에서 첫번째 요소로 바로 이동할 수 있도록) 어느쪽으로 넘겨야 더 빨리 원하는 카드로 돌아갈 수 있는지 확인할 수 있는 정보의 역할도 한다고 생각해요.

2023-03-22 08:00 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +                key={`${JSON.stringify(item)}+${index}`}
기기에 따라 달라질 필요는 없을 것 같아요. 제가 알기로는 dot를 이용해 표시하는 방법과 선민님이 제시해주신 방식이 쓰이면 좋은 곳이 각각 다를 것 같아서, 그냥 나중에 필요하다면 선민님이 제시해주신 방식도 추가로 구현하던가 하면 될 것 같아요. 전자는 인스타그램처럼 단순히 여러 장 첨부된 사진을 볼 때, 후자는 지금 레퍼런스처럼 이벤트 배너같은 것들을 나열할 때 어울릴 것 같네요.  
그 외에는 세영님하고 대체로 같은 생각이에요!

2023-03-23 14:40 UTC, se030 approved these changes
고생하셨습니다 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
리뷰할게 자잘한 것밖에 없어요 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2023-03-23 14:40 UTC, se030 commented on src/components/Carousel/index.tsx
> +  }
이 제안 반영이 되지 않은 것 같아요! 반영한 리뷰들은 resolve 하시면 더 편하게 확인할 수 있어요 ~

2023-03-23 14:40 UTC, se030 commented on src/components/Carousel/index.tsx
> +    line === 1 ? CAROUSEL_SLIDE_STYLE.inline : CAROUSEL_SLIDE_STYLE.multiline;
`CAROUSEL_SLIDE_STYLE[line === 1 ? 'inline' : 'multiline']` 이 줄바꿈도 없고 읽기도 편한 것 같아요!

2023-03-23 14:40 UTC, se030 commented on src/components/Carousel/index.tsx
> +    line === 1 ? totalChildren : Math.ceil(totalChildren / line);
여기도 `Math.ceil(totalChildren / line)` 이거랑 같아보이는데 아닌가요?
불필요한 ceil 호출을 막기 위해서라면 line === 1 조건문을 렌더부에도 계속 사용해서 isInline 같은 변수로 하나 만들어도 좋을 것 같아요!

2023-03-23 14:40 UTC, se030 commented on src/components/Carousel/index.tsx
> +  const scrollEventHandler = debounce(() => {
아까 현빈님께도 말씀드렸는데, 저희 핸들러 네이밍 컨벤션이 `onVerb`에요. (회의록 가면 확인할 수 있어요.)

```tsx
<NavigationButton
    clickHandler={() => setCurrentPage(currentPage - 1)}
    disabled={currentPage === 0}
>
```
이쪽 props 네이밍들도 맞춰서 사용하면 좋겠어요!

2023-03-23 14:40 UTC, se030 commented on src/components/Carousel/index.tsx
> +          <ItemList ref={scrollRef} onScroll={() => scrollEventHandler()}>
```tsx
<ItemList ref={scrollRef} onScroll={scrollEventHandler}>
```
로 사용할 수 있도록 scrollEventHandler 자체를 콜백으로 만들어주면 어때요?

2023-03-23 14:42 UTC, se030 commented on src/components/Carousel/Carousel.stories.tsx
> +export const Slide = SlideTemplate.bind({});
```suggestion
export const Slide = SlideTemplate.bind({});
```

마지막으로 이 스토리가 미관상 너무 눌려있어서(?) height를 좀 넣어주면 docs 볼 때 기분이 더 좋을 것 같아요 ~~~

2023-03-23 15:08 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +    line === 1 ? totalChildren : Math.ceil(totalChildren / line);
헉 ㅋㅋㅋㅋㅋㅋ 이런 실수를..
celi 많이 호출하면 성능상의 문제가 있을까요??

2023-03-23 15:12 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +  }
엇 이거 말하시는건줄 알고 넣었는데 -ms-overflow-style: none;  이게 아닌가여??

2023-03-23 15:34 UTC, se030 commented on src/components/Carousel/index.tsx
> +    line === 1 ? totalChildren : Math.ceil(totalChildren / line);
움 저는 무거운 연산 아니라서 상관없을 것 같다는 의견 ...! 혹시 의도적으로 하신건가 했어요 ㅋㅋㅋㅋㅋ

2023-03-23 15:42 UTC, se030 commented on src/components/Carousel/index.tsx
> +  }
에엥 아까는 왜 안보였죠 맞아요 ㅠㅠㅠ

2023-03-23 16:35 UTC, prayinforrain requested changes
고생하셨어요!

작은 버그가 있는데..ㅎㅎ..
NavigationButton으로 페이지 이동 -> `scrollEventHandler` 디바운스 타이머 시작 -> 타이머가 끝나기 전에 한번 더 눌러 페이지 이동
이런 상황에서 자꾸 이전 카드로 돌아오는 것 같아요. 간단히 말하면 네비게이션 버튼을 막 광클하면 덜컹덜컹해요.

이것만 해결되면 다른 문제는 없는 것 같아요! 너무 좋아요

2023-03-23 18:59 UTC, iyu88 approved these changes
수고많으셨어요~~ 
무수히 많은 Conversation을 처리하느라 고생하셨습니다.
👍👍👍

2023-03-23 18:59 UTC, iyu88 commented on src/components/Carousel/NavigationButton.tsx
> +  border-radius: 1.3rem;
마이너한 부분인데요,
radius 가 둥근 것을 표현하고 싶다고 이해했어요.
1.3rem 보다 50% 처럼 써주는게 
_원형이구나_ 를 바로 파악하기 좋을 것 같아요.

2023-03-23 18:59 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  if (window.innerWidth / newCardSize.WIDTH <= 1.2) {
여기는 왜 1.2랑 비교하는건가요? 🤔
특별히 1.2인 이유가 있으면 상수에 담아서 어떤 걸 의미하는지 알려줘도 좋을 것 같아요

2023-03-23 18:59 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +    });
scrollIntoView 좋아요 🥹👍

2023-03-23 18:59 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  if (!context) return <></>;
여기 PR 한 번 참고해서 Context 를 커스텀 훅으로 빼보셔도 좋을 것 같아요~

https://github.com/c-h-w-h/cds/pull/67

```
const useTabs = () => {
  const context = useContext(TabsContext);
  if (context === null) {
    throw new Error('useTabs should be used within Tabs');
  }
  return context;
};
```

2023-03-24 11:10 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +  if (window.innerWidth / newCardSize.WIDTH <= 1.2) {
앗 이거 카드 하나가 viewport width에 거의 꽉차는 상황일 때 카드를 화면 중앙에 오게 처리해줄려고 한거였어요! 거의 꽉 차는 기준이 window width가 카드 width 의 1.2배일 때 기준으로 그렇게 처리해줘요..!! 확실히 이렇게만 보면 코드가 뭔소린지 알아보기 어렵네요ㅜㅜ 따로 util함수로 빼겠습니다!

2023-03-24 16:05 UTC, prayinforrain approved these changes
너무 고생하셨어요 ㅎㅎ..... 면목없네요  
두 가지만 반영해 주시구.. 혹시 주말에 제가 늦게 확인하면 곤란하니 approve는 미리 꽂아 둘게요..

2023-03-24 16:05 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +  translateX: number;
좋아요~ 코드 읽기가 훨씬 쉬워졌어요 감사합니다

2023-03-24 16:05 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +  };
죄송해요 선민님.. 놓쳤어요 😭
지금 throttle 안의 코드가 작동하지 않아요. 실제로 `currentPage`가 이동하는 이유는 `scrollEventHandler` 때문이에요. 너무 죄송해서 suggestion 가지고 왔어요..  
시간을 500으로 늘린 이유는 smooth scroll에 걸리는 시간이 200ms가 넘어가서 throttle하는 의미가 없어 보여서 넉넉하게 줬어요. cardWidth 값에 따라 스크롤에 걸리는 시간이 조금씩 다른데 적정선을 못찾겠어요.

```suggestion
  const scrollToPage = throttle((current: number) => {
    setTimeout(() => {
      cardsRef.current?.children[current * line].scrollIntoView({
        inline: 'start',
        behavior: 'smooth',
      });
    });
  }, 500);
```

2023-03-24 16:05 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +  margin-right: ${({ gap }) => pixelToRem(`${gap}px`)};
이거 언젠가 논의하고 싶었는데.. 본 김에 메모차 적어둘게요. 혹시 다음 회의 때 제가 얘기 안하면 누가 떠올리게 해 주세요..
[이 글](https://simsimjae.medium.com/%ED%81%AC%EB%A6%AC%EC%8A%A4%EB%A7%88%EC%8A%A4%EC%97%90-%EC%BD%94%EB%94%A9%ED%95%98%EA%B3%A0-%EC%9E%88%EB%8A%94-%EB%82%B4-%EC%9D%B8%EC%83%9D%EC%9D%B4-%EB%A0%88%EC%A0%84%EB%93%9C-%EA%B0%99%EC%A7%80%EB%A7%8C-%EC%98%A4%EB%8A%98%EB%8F%84-%EB%8B%AC%EB%A6%B0%EB%8B%A4-96f79ee41464)에서 봤는데, 글자가 아닌 것에 rem을 사용하는 것이 부정적인 결과를 초래할 수 있다는 것 같아요. 개발자에게서 props로 이미 픽셀로 받은 크기 값들까지 꼭 rem으로 변환해줘야 할 필요가 있을까요?  
사실 rem으로 변환하는 과정도 일반적인 브라우저 기본 설정이 `1rem = 16px`로 되있어서 그렇지 변경될 수 있는 값이라 정확한 변환도 아니에요.

2023-03-24 16:05 UTC, prayinforrain commented on src/components/Carousel/index.tsx
> +    setCurrentPage(0);
지금 window 사이즈 변경시 dot만 초기화되고 카드는 그대로인데, 제 생각이 맞다면 요것도 `scrollToPage`로 변경해야 할 것 같아요.(테스트 필요)

2023-03-27 04:48 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +  };
확인했습니당

2023-03-27 04:48 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +    setCurrentPage(0);
확인했습니당

2023-03-27 04:48 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +  margin-right: ${({ gap }) => pixelToRem(`${gap}px`)};
좀이따 회의때 다른 분들이랑 얘기해보구 반영할게요~~

2023-03-27 10:28 UTC, iyu88 approved these changes
수정사항만 반영하고 합치면 될 것 같아요~
고생 많으셨습니다!

2023-03-27 10:28 UTC, iyu88 commented on src/components/Carousel/NavigationButton.tsx
> +    &:enabled:hover {
원래 이랬는지 기억이 잘 안나지만 CSS 활용이 너무 좋아요.
다른 곳도 이런 식으로 바꿔야 할 것 같아요. (이슈를 만들어야 할 것 같은...)
밑에 관련 블로그 링크랑 MDN 문서 메모해놓을게요 ㅎㅎ

[@media (hover: hover) ](https://www.kenrhee.com/til/media-hover)
[:enabled](https://developer.mozilla.org/en-US/docs/Web/CSS/:enabled)

2023-03-27 10:28 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +    translateX: newCardSize.gap + Math.floor(newCardSize.cardWidth / 5),
`Math.floor(newCardSize.cardWidth / 5)`
이 값은 Offset 값으로 이해했는데 맞을까요?

2023-03-27 10:28 UTC, iyu88 commented on src/components/Carousel/index.tsx
> +  const { cardWidth, gap, cardHeight, translateX } = context;
이미 useCarouselContext 내부에서 null일 경우에 에러를 던지고 있어서 

`const { cardWidth, gap, cardHeight, translateX } = useCarouselContext();`

이렇게 줄이면 좋을 것 같아요!

나머지 컴포넌트들에서도요~

2023-03-27 13:46 UTC, leesunmin1231 commented on src/components/Carousel/index.tsx
> +    translateX: newCardSize.gap + Math.floor(newCardSize.cardWidth / 5),
네 맞아요!! 카드 처음 시작하는 offset 값이에요

2023-03-27 13:52 UTC, merged