Feat/modal: Modal 컴포넌트 리팩토링
c-h-w-h/cds pull request #97
Opened 2023-04-04 05:03 UTC by leesunmin1231

## 🤠 개요

#93 : Modal 박스 내부 컴포넌트는 children만 받는 방식으로 수정했습니다.

## 💫 설명

### Props
- isOpen: 모달 열고 닫는 상태
- onClose: 모달 닫는 핸들러

모달 내부 내용은 children으로 넣어주면 됩니다.
모달 컴포넌트의 기능은 children으로 넣어준 컴포넌트 들을 기존 화면 위로 띄워주는 기능만 합니다.

스토리북은 현빈님이 작업 해놓으신 다른 컴포넌트 스토리북 참고해서 description 달아 놓았는데, 추가할 부분이나, 수정사항 있으면 피드백 남겨주세요!

## 📷 스크린샷 (Optional)
<img width="1169" alt="image" src="https://user-images.githubusercontent.com/81913106/229691512-8ba0c930-c8ca-4c87-83ee-77b146aa59c1.png">

2023-04-05 02:56 UTC, se030 approved these changes
고생하셨습니다! 사용법이 훨씬 깔끔하네요 👍🏻
컴파운드 패턴 사용해보는걸로 UI 로직이 어디까지인지 생각하는 연습이 되는 것 같아요 ... 추가로 모달도 Portal로 띄우면 더 좋을 것 같은데, 기존 Portal 설계.. 사용 방식에 수정이 좀 필요해서 우선 스킵해야 할 듯 ..ㅎㅎㅎㅎ

2023-04-05 02:56 UTC, se030 commented on src/components/Modal/Modal.stories.tsx
>    const [{ isOpen }, updateArgs] = useArgs();
이 부분은 useState로 바꾸면 어때요? 어떻게 사용하는지 알고싶다고 했을 때 평소 사용하는 훅으로 보여지는게 더 쉬운 것 같아서요 ~

2023-04-05 06:56 UTC, iyu88 requested changes
![스크린샷 2023-04-05 15 52 53](https://user-images.githubusercontent.com/31645195/230004008-eeb677f9-94d3-4e51-9b92-62e685be3133.png)

Modal 나타났을 때 하얀 버튼들이 눌리네요

![스크린샷 2023-04-05 15 55 46](https://user-images.githubusercontent.com/31645195/230004226-6876ec78-2b90-409a-9d6c-b28ac227aca5.png)

위에 있는 태그에 z-index를 주변 나아지는 것 같은데 확인 부탁드려요~

2023-04-05 06:56 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
> +        type: { summary: false, required: true },
summary 값을 boolean 으로 변경해주세요~

2023-04-05 06:56 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
> +    },
onClose 는 사용자가 굳이 조절하지 않아도 될 것 같아서 

```jsx
onClose: {
      name: 'onClose',
      description: 'Modal을 닫는 setState 함수입니다.',
      control: false,
 },
```
control: false 하면 좋을 것 같아요!

2023-04-05 06:56 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
>    },
![스크린샷 2023-04-05 15 48 40](https://user-images.githubusercontent.com/31645195/230002677-c8d966d8-e23c-48bf-bd4d-4455617c1009.png)

어디선가 actions 랑 title 이 나타났는데,
Modal 컴포넌트에서 Props로 받는 값이 아닌 것 같아서
onClose랑 같은 레벨에

```
title: { table: { disable: true } },
actions: { table: { disable: true } },
```
추가하면 Table에서 숨길 수 있겠어요

2023-04-05 06:56 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
>      <div>
사소한! 것인데요
Fragment 로 해도 괜찮을 것 같아요

2023-04-05 06:58 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
>      <div>
댓글이 이상하게 달렸어요
return 할 때 말씀드린 거였어요

2023-04-05 12:37 UTC, prayinforrain commented on src/components/Modal/Modal.stories.tsx
>    },
이거 이 PR에서 삭제된 props인데, 혹시 스토리북 실행된 상태에서 checkout하셨다면 핫리로드로 갱신이 완전히 되지 않아서 생기는 일시적인 버그일수도 있을 것 같아요. 다시 한 번만 확인 부탁드려요!

2023-04-05 12:47 UTC, leesunmin1231 commented on src/components/Modal/Modal.stories.tsx
>    },
엥 이거 왜이러는지 모르겠는데, 삭제한 props인데 스토리북에서 안없어져요...

2023-04-05 13:07 UTC, prayinforrain approved these changes
고생하셨어요~ 엄청 간단해졌네요  
모달에 대한 접근성 속성도 아직 추가가 안되어 있다면 이 PR에서 같이 추가해주면 좋을 것 같아요! 언젠간 해야 할 일이니.. 레퍼런스 달아둘게요.
https://nuli.navercorp.com/community/article/1133131



```
// index.tsx
const Content = styled.div`
  height: min-content;
  margin: 1rem 0;
`;

const Footer = styled.div`
  width: 100%;
  margin-top: 2rem;
  justify-content: space-between;
`;
```

changes가 아니어서 이 부분에 코멘트를 달 수가 없는데, unused vars가 되어서 지워주시면 좋을 것 같아요!

2023-04-05 14:05 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
>    },
그렇네요 로컬 문제였던 것 같아요
감사해요 ㅎㅎ

2023-04-05 14:07 UTC, iyu88 approved these changes
LGTM

2023-04-05 14:43 UTC, se030 commented on src/components/Modal/index.tsx
> +    <Portal>
선민님 ㅎㅎ Portal 사용할 때 이제 id를 필수로 넣어야하는데, 모달용 PORTAL_ROOT_ID 만들고 CdsProvider에 root div 추가해줘야해요

현빈님 작업 참고하시면 될 것 같아요! https://github.com/c-h-w-h/cds/pull/90/commits/442127f8b1d2cc334512992db3563450e46fddd1

2023-04-22 13:32 UTC, se030 approved these changes

2023-04-22 13:32 UTC, se030 commented on src/components/Modal/index.tsx
> +const Content = ({ children }: DefaultPropsWithChildren<HTMLDivElement>) => {
children 속성만 사용하는거라면 ChildrenProps로 변경해주세요! 뒤늦게 추가돼서 홍보(?)가 덜 됐어요 ...

2023-04-22 13:32 UTC, se030 commented on src/components/Modal/index.tsx
> +const TobBar = ({ title }: TobBarProps) => {
얘는 TopBar가 되어야 하는 것 같은데 맞나요? ㅎㅎ 하나 제안드리면 개인적으로는 컨텐츠 영역이 Modal.Content라서 Content - Header 인터페이스가 더 익숙한 것 같아요.

2023-04-22 13:32 UTC, se030 commented on src/components/Modal/Modal.stories.tsx
> +export const WithTobBar = TobBarTemplate.bind({});
사소한거지만 재사용할 목적이 아니라면 개별 스토리의 템플릿은 분리할 필요가 없다고 생각해요. 그리고 전체 스토리 description에 구성 요소 컴포넌트들에 대한 설명이 추가되면 좋겠어요!

2023-04-23 06:50 UTC, leesunmin1231 commented on src/components/Modal/index.tsx
> +const TobBar = ({ title }: TobBarProps) => {
옹 좋아요 변경할게요!

2023-04-23 14:58 UTC, iyu88 approved these changes
Modal.Header 가 생긴게 너무 귀엽네요~
수고 많으셨습니다!
코멘트만 확인 부탁드릴게요~

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
> +  title: 'Design System/Components/Modal',
ㅠㅠ 제가 늦게 Template 올리는 바람에..
사이드바 depth 를 줄이기로 했습니다!
`Design System` 을 삭제헤주세요~

```suggestion
  title: 'Components/Modal',
```

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
> +      'Modal은 특정 컨텐츠가 담긴 화면을 다른 화면 위로 띄워줍니다.',
```suggestion
      'Modal은 사용자의 주의를 끌거나 추가적인 정보를 제공하는 경우 특정 컨텐츠가 담긴 요소를 화면의 맨 위로 띄워줍니다.',
```

설명을 조금 더 다듬어 보았습니다. 

'띄워줍니다'를 '~화면 위에 표시합니다' 이런 식으로 변경해도 될 것 같구요.

선민님께 맡기겠습니다! ㅎㅎ

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
> +      },
```suggestion
table: {
    type: { summary: 'boolean', required: true },
    defaultValue: { summary: true },
      },
```

이렇게 변경해야 table에 정상적으로 뜰 것 같아요

그나저나 default가 true인가요?? 👀

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/Modal.stories.tsx
> +const ModalContent = ({
이거는 스토리용이 맞을까요?

컴포넌트니까 Dummy 접두사가 붙어있으면 좋을 것 같아요!

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/index.tsx
> +          <BackGround onClick={onClose} />
회색 배경을 의미하는 것 같은데 

Dimmed 라는 이름은 어떠신가요?

제안드려봅니다~ ㅎㅎ

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/index.tsx
> +            <ModalBox role="dialog" aria-modal="true">
모달의 접근성은 이렇게 생겼군요~
칭찬해요 👍

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/index.tsx
> +    </HeaderWrapper>
```suggestion
<Flexbox
      justifyContent='left'
      css={css`
        height: 50px;
        padding: 20px;
        border-bottom: 1px solid ${themeColor.gray100};
      `}
    >
      <Button onClick={onClose}>
        <Center>
          <MdArrowBackIosNew />
        </Center>
      </Button>
      <Typography variant="body">{title}</Typography>
    </Flexbox>
```

기존에 있는 컴포넌트들을 활용해보았어요.

align-items랑 line-height 는 각가 삭제하거나 변경해도 변화가 눈에 안보여서 없애보았는데,

한 번 검토 부탁드려요!

2023-04-23 14:58 UTC, iyu88 commented on src/components/Modal/index.tsx
> +    &:enabled:hover {
enabled 를 추가하면 어떻게 되나요?? 👀

2023-04-24 05:06 UTC, leesunmin1231 commented on src/components/Modal/Modal.stories.tsx
> +      'Modal은 특정 컨텐츠가 담긴 화면을 다른 화면 위로 띄워줍니다.',
우왕 좋아요 반영할게요!

2023-04-24 05:13 UTC, leesunmin1231 commented on src/components/Modal/Modal.stories.tsx
> +      },
헉 아뇨 defautValue 없어요! 지워야겠네요 감사해요~~

2023-04-24 05:13 UTC, leesunmin1231 commented on src/components/Modal/Modal.stories.tsx
> +const ModalContent = ({
맞아요! 반영할게요~~

2023-04-24 05:28 UTC, leesunmin1231 commented on src/components/Modal/index.tsx
> +          <BackGround onClick={onClose} />
오 좋아요!! 반영할게요~~

2023-04-24 05:31 UTC, leesunmin1231 commented on src/components/Modal/index.tsx
> +    </HeaderWrapper>
옹 잘 동작해요!! 감사해요 반영할게요!!

2023-04-24 05:36 UTC, leesunmin1231 commented on src/components/Modal/index.tsx
> +    &:enabled:hover {
아이쿠 여기서는 필요없는 거네요 빼야겠어요.
button disabled 될때 cursor pointer 안되게 하려구 해놓은 거에요.
근데 이방법 보다는 그 세영님 pr처럼 disabled일때 cursor: not-allowed;가 더 깔끔해욤

2023-04-24 07:22 UTC, merged