Refactor/button: Button 컴포넌트 리팩토링
c-h-w-h/cds pull request #98
Opened 2023-04-04 17:29 UTC by se030

## 🤠 개요

- Closes #96 

- Button 컴포넌트 리팩토링 작업입니다. 고민되는 것들이 있어서 점검 후 Draft 풀겠습니다.

## 💫 설명

- ButtonVariant 타입에 `"plain"`이 추가되었습니다. 네이밍 의견 환영합니다 ...

- props에 HTML button 기본 속성인 `type`, aria-label로 사용하기 위한 `label`을 추가했습니다.

## 📷 스크린샷 (Optional)

2023-04-05 04:44 UTC, prayinforrain commented
>아이콘 관련 props가 너무 많고 직관적인 사용이 어렵다는 나쁜 느낌이 들어요. 초반에 IconTypography가 찝찝했던 이유와 같아요.

동의해요. 지금 떠오르는 방법만 대충 정리해 볼게요.
- iconSize는 사실 react-icons에서 `1em`을 기본값으로 주고 있기 때문에 사실 Typography 들어가는 부분만 조금 손본다면 따로 지정하지 않아도 text와 글자크기를 맞추거나 - Button 컴포넌트 자체에서 그냥 textSize로 받아서 통일해 줄 수 있을 것 같아요. 우리 아이콘이 react-icons 컴포넌트만 받는 건 아니지만 이미지 아이콘도 비슷하게 맞추기 쉬우니까 이 예시만 들었어요.
- iconPosition이 `left | right` 뿐이라면 차라리 leftIcon, rightIcon으로 받는게 나을 수도 있지 않을까.. 이건 chakra UI에서 사용하는 방법이에요.
- iconTranslateY는 지금 보니 없어도 되지 않나 하는 생각이 들어요. 윈도우만 그런지 모르겠는데 지금 적용된 스토리 보면 좀.. 위로 쏠려있어요.

그리고 사용 방법에 대해서는.. children을 받는게 native HTML같아서 더 직관적이긴 한데 실제 사용된 코드를 보면 Props로 받는게 더 가독성이 좋을 것 같아서, 취향차이(?)이지 않을까.. 😅

>현재 Button 컴포넌트에는 button 태그와 a 태그가 사용되고 있어요. 링크의 역할을 하는 요소와 버튼이 동일한 디자인을 가지는 경우가 많아서인데요.

걱정되는 부분이 있어요. button과 anchor는 서로 다른 역할을 가지고 있고, 분리되어야 한다고 생각해요. 물론 버튼 모양을 한 링크 - plain Text 버튼이 필요할 수는 있지만, 이걸 Button이라는 이름의 컴포넌트가 지원한다면 이름은 버튼이지만 a태그의 역할을 하거나, a태그로 이루어진 요소가 되어 혼동을 줄 것 같아요. 물론 디자인이 중심이 되어야겠지만 Button 컴포넌트가 a 태그까지 관리하는 건 약간 범위를 넘는(?) 것 같아요.
둘을 분리한다면 말씀하신 문제가 해결될 것 같은데, 어떻게 생각하시는지 궁금해요!

지금 코드 볼 상황이 아니어서 리뷰는 조금만 나중에 할게요 😭

2023-04-05 05:41 UTC, se030 commented
> 그리고 사용 방법에 대해서는.. children을 받는게 native HTML같아서 더 직관적이긴 한데 실제 사용된 코드를 보면 Props로 받는게 더 가독성이 좋을 것 같아서, 취향차이(?)이지 않을까.. 😅

ㅋㅋㅋㅋㅋㅋ 취향 차이가 맞는 것 같아요 ... 제 취향이 확고하지 못할뿐 .. 말씀하신대로 스타일 관련 props들은 제거해도 괜찮을 것 같아요. 내부 배치를 선언적으로 보여주는건 네이티브 인터페이스라는 생각도 들고 ..ㅎㅎ Icon 컴포넌트가 이미 만들어져 있어서 사용자가 가져다 사용하면 되거든요.

> 걱정되는 부분이 있어요. button과 anchor는 서로 다른 역할을 가지고 있고, 분리되어야 한다고 생각해요. 물론 버튼 모양을 한 링크 - plain Text 버튼이 필요할 수는 있지만, 이걸 Button이라는 이름의 컴포넌트가 지원한다면 이름은 버튼이지만 a태그의 역할을 하거나, a태그로 이루어진 요소가 되어 혼동을 줄 것 같아요. 물론 디자인이 중심이 되어야겠지만 Button 컴포넌트가 a 태그까지 관리하는 건 약간 범위를 넘는(?) 것 같아요. 둘을 분리한다면 말씀하신 문제가 해결될 것 같은데, 어떻게 생각하시는지 궁금해요!

비슷한 부분에서 찝찝한 마음이 들었어요. 그리고 어찌됐든 네이티브 속성들을 props로 사용할 수 있어야 하는게 맞다고 생각해요.
LinkButton 정도로 분리해보면 어떨까요 ..? 라이브러이에서 제공하는 형태를 공유한다 점이 어느정도 드러났으면하고, Link/Anchor로 분리하기에는 텍스트 내부에 포함되는 링크 등등과 구분될 필요가 있다고 생각돼서요.

2023-04-05 08:14 UTC, iyu88 requested changes
-- 아이콘 관련

아이콘 관련해서 분리해도 괜찮지만 일단 둬도 괜찮을 것 같아요.
개인적으로 props 이름으로 충분히 잘 읽히고 가독성이 완전 (매우) 나쁜 편은 아닌 것 같아요. 
props를 왕창 사용하고 있는 버튼들을 아직 못봐서 그런 것일 수도 있지만요.

-- 링크 관련 

원래는 Button(Anchor)에 href와 onClick가 동시에 부여해도 되나 싶어서 찾아보니까 
그렇게 하는 경우가 더러 있는 것 같더라구요.
어색하다고 생각했는데 괜찮을 것 같기도 해요.
근데 또 생각이 드는게 form에 있는 버튼에 href가 있다면?
뭔가 막을 방법이 있을까요? 🤔

2023-04-05 08:14 UTC, iyu88 commented on src/components/Button/Button.stories.tsx
> +        type: { summary: 'ButtonVariant' },
defaultValue: { summary: 'square' }
추가가 필요해 보입니다.

2023-04-05 08:14 UTC, iyu88 commented on src/components/Button/Button.stories.tsx
> +      },
```
table: {
  type: { summary: 'string', required: true },
},
control: {
  type: 'text'
}
```
Default 스토리에 label 값이 고정되어 있어서 
수정하신다면 label 을 arg 로 받도록 같이 수정하시면 될 것 같아요

2023-04-05 08:14 UTC, iyu88 commented on src/components/Button/Button.stories.tsx
> +        type: { summary: 'ButtonVariant' },
type: { summary: 'string' }
이 맞을까요..?

2023-04-05 08:14 UTC, iyu88 commented on src/components/Button/index.tsx
> +  const { white, primary200, primary400, gray200 } = color;
color 로 바꾸신 이유가 있을까요?
다른 컴포넌트들도 이렇게 바꿔야 할까 싶어서요!

2023-04-05 08:14 UTC, iyu88 commented on src/components/Button/index.tsx
> +  const isSquare = !variant.includes('round');
`const isSquare = variant.includes('square');`
로 쓰는게 조금 더 자연스러워 보여요.

2023-04-05 08:57 UTC, se030 commented on src/components/Button/index.tsx
> +  const { white, primary200, primary400, gray200 } = color;
음 이건 이유가 있는게 아니라 모듈 쪼개고 다시 합치면서 변수명이 바뀐 것 같아요.
굳이 재할당 안해도 될 것 같은데 .. 보니까 모든 컴포넌트에서 themeColor로 사용하고 있어서 통일할게요!

2023-04-05 08:57 UTC, se030 commented on src/components/Button/index.tsx
> +  const isSquare = !variant.includes('round');
default 옵션이 square로 변경되면서 이렇게 됐어요 ..ㅎㅎ

2023-04-05 12:31 UTC, leesunmin1231 approved these changes
많은 고민의 흔적이 느껴져요.. ㅎㅎ 고생하셨습니다~~~

2023-04-05 12:31 UTC, leesunmin1231 commented on src/components/Button/Button.stories.tsx
> +    text="상장하기"
이번에 버튼 써보면서 느낀건데, 그 html button 태그처럼 text를 props말고 children으로 줄 수 있으면 좋겠어요..!! button은 당연히 이렇게 동작하겠지 하는 부분들은 그렇게 동작해야 사용하기 편할거 같아요!

2023-04-05 13:40 UTC, se030 commented on src/components/Button/Button.stories.tsx
> +    text="상장하기"
반영하겠습니다!

2023-04-23 04:16 UTC, leesunmin1231 approved these changes
고생하셨어요~~!! 훅으로 스타일 로직 분리해주셔서 코드 읽기 편했어요. 굿굿 👍

2023-04-23 04:16 UTC, leesunmin1231 commented on src/components/Button/index.tsx
> +  children: TextNode;
훨씬 깔끔해졌어요!! 너무 좋아요~~~

2023-04-23 04:16 UTC, leesunmin1231 commented on src/components/ButtonLink/index.tsx
> +const ButtonLink = ({
이왕 다른 컴포넌트로 분리한거, 조금 더 직관적으로 ButtonLink 대신 그냥 Link 어때요?

2023-04-23 05:05 UTC, se030 commented on src/components/ButtonLink/index.tsx
> +const ButtonLink = ({
기본 링크는 아니고 버튼 디자인을 가진 애니까 ~~라고 생각해서 이렇게 했는데 Link가 나을까요 ..??

2023-04-23 16:04 UTC, iyu88 approved these changes
수고하셨어요~
코멘트만 확인 부탁드립니다

2023-04-23 16:04 UTC, iyu88 commented on src/components/Button/Button.stories.tsx
> +  title: 'Design System/Components/Button',
```suggestion
  title: 'Components/Button',
```

이렇게 부탁드립니다!

2023-04-23 16:04 UTC, iyu88 commented on src/components/Button/useButtonStyle.tsx
> +          border: 0.125rem solid ${primary200};
기억이 가물가물한데 저번에 글자에만 rem 단위를 사용하기로 했던 것 같아서 
px 단위로 변경하는건 어떨까요?

\+
contentStyle 에서도요!

\+
반환값에서도요!

2023-04-23 17:16 UTC, prayinforrain approved these changes
>지금 코드 볼 상황이 아니어서 리뷰는 조금만 나중에 할게요 😭

나중에라고 해놓고 3주 지나서 보는 스스로가 얼탱이가 없네요..

2023-04-23 17:16 UTC, prayinforrain commented on src/components/Button/useButtonStyle.tsx
> +          }
이거 나중에 흰색 배경도 같이 색이 변했으면 좋겠어요. 저는 보통 filter: brightness를 사용하긴 하는데 나중에 컬러 팔레트가 고쳐지면 수정해요!

2023-04-23 17:16 UTC, prayinforrain commented on src/components/Button/Button.stories.tsx
> +  argTypes: {
처음 스토리 열고 조금 놀랐는데, `ButtonLink` 컴포넌트의 props를 카테고리로 나누거나 하면 좋을 것 같아요.  
아니면 두 컴포넌트의 스토리를 분리하는게 더 좋을 수도? 있을 것 같아요.

2023-04-23 17:16 UTC, prayinforrain commented on src/components/ButtonLink/index.tsx
> +const ButtonLink = ({
이성은 `Link`라는 이름이 맞다고 하는데 감성은 극렬히 반대해요..
사실 Link라는 이름의 컴포넌트가 Next.js에 있어서 괜히 그런 것 같기도 하고, 아니면 아예 Link 컴포넌트를 만들어서 variant를 넣어야 하나 싶기도 하고 그래요.

2023-04-23 17:16 UTC, prayinforrain commented on src/components/Button/useButtonStyle.tsx
> +          &.disabled {
disabled라는 className을 지원해야 하나요?  
보통 지원하는 것 같기는 한데 필요한가? 싶어서 다른 작업 때는 안했거든요. 뭔가 권고사항같은게 있다면 다른 곳에도 반영할까봐요.

2023-04-24 02:55 UTC, se030 commented on src/components/Button/useButtonStyle.tsx
> +          &.disabled {
이건 ButtonLink 컴포넌트 스타일링 때문에 있는거에요 ..!

2023-04-24 05:39 UTC, leesunmin1231 commented on src/components/ButtonLink/index.tsx
> +const ButtonLink = ({
흠 컴포넌트 내부에 딱 a 태그만 있으니까 한눈에 기능을 알아보기에는 Link라는 네이밍이 더 적절한거 같아요

2023-04-24 08:56 UTC, merged